# Generated by Django 5.2.6 on 2025-09-13 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('capitan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camisa', models.PositiveSmallIntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_asociados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateTimeField()),
                ('lugar_partido', models.TextField()),
                ('marcador_local', models.PositiveIntegerField(default=0)),
                ('marcador_visitante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en juego', 'En juego'), ('finalizado', 'Finalizado'), ('programado', 'Programado')], default='programado', max_length=15)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='api.equipotorneo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='api.equipotorneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partido',
                'ordering': ['fecha_partido'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica_torneo_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField()),
                ('partidos_ganados', models.PositiveIntegerField()),
                ('partidos_empatados', models.PositiveIntegerField()),
                ('partidos_perdidos', models.PositiveIntegerField()),
                ('goles_favor', models.PositiveIntegerField()),
                ('goles_contra', models.PositiveIntegerField()),
                ('goles_diferencia', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='equipotorneo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.torneo'),
        ),
    ]
