# Generated by Django 5.2.6 on 2025-10-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estadisticaequipo_estadisticajugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='capitan',
        ),
    ]
