# Generated by Django 5.2.6 on 2025-10-27 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_equipo_capitan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='numero_camisa',
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default=1989, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='numero_camiseta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
