# Generated by Django 5.2.6 on 2025-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_jugador_jugador_remove_jugador_numero_camisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('registro', 'Registro'), ('equipos', 'Registro de equipos'), ('jugadores', 'Registro de jugadores'), ('formato', 'Configuración del formato'), ('activo', 'En curso'), ('finalizado', 'Finalizado')], default='registro', max_length=20),
        ),
    ]
