# Generated by Django 5.2.6 on 2025-11-06 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_torneo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('todos', 'Todos contra todos'), ('eliminacion', 'Eliminación directa'), ('grupos', 'Por grupos')], default='eliminacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('registro', 'Registro'), ('activo', 'En curso'), ('finalizado', 'Finalizado')], default='registro', max_length=20),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_organizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
