# Generated by Django 5.2.6 on 2025-11-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_torneo_formato_alter_torneo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fecha_partido', 'jornada', 'ronda'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='jornada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='ronda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_partido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='lugar_partido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
