# Generated by Django 5.2.6 on 2025-10-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
